plugins {
    alias(libs.plugins.android.application)
}
android {
    namespace "com.oea.launcher"
    buildFeatures { aidl true }
    compileSdk 36
    defaultConfig {
        applicationId "com.oea.launcher"
        minSdk 26
        targetSdk 36
        versionCode 4
        versionName "0.2.0-alpha4"
    }
    buildTypes { release { minifyEnabled false; signingConfig signingConfigs.debug } }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}
kotlin { jvmToolchain(21) }

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.kotlinx.coroutines.android
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
