name: OEA write permission test
on:
  push:
    branches: [main]
jobs:
  test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "runner and write permission active"
